# Generated by Django 2.2.6 on 2019-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.BigIntegerField(max_length=11)),
                ('name', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
            ],
        ),
    ]
